backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img

collections:
  - name: config
    label: Config
    delete: false
    editor:
      preview: false
    files:
      - name: general
        label: Site Config
        file: content/config.json
        description: General site settings
        fields:
          - name: url
            label: URL
            widget: string
            hint: Do not enter the trailing slash of the URL
          - name: title
            label: Site title
            widget: string
          - name: description
            label: Site description
            widget: string
          - name: keywords
            label: Site keywords
            widget: list
            summary: '{{fields.keyword}}'
            field:
              label: Keyword
              name: keyword
              widget: string

  - name: animals
    label: Animals
    label_singular: Animal
    folder: content/meta/animals
    extension: json
    format: json
    editor:
      preview: false
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{name}}'
    fields:
      - name: slug
        label: Slug
        widget: string
        hint: The part of a URL identifies the animal
      - name: name
        label: Title
        widget: string
        hint: Animal name for displaying on the site

  - name: categories
    label: Categories
    label_singular: Category
    folder: content/meta/categories
    extension: json
    format: json
    editor:
      preview: false
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{name}}'
    fields:
      - name: slug
        label: Slug
        widget: string
        hint: The part of a URL identifies the category
      - name: name
        label: Title
        widget: string
        hint: Category name for displaying on the site

  - name: pages
    label: Pages
    label_singular: Page
    folder: content/pages
    extension: json
    format: json
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      - name: slug
        label: Slug
        widget: string
        hint: The part of a URL identifies the page
      - name: title
        label: Title
        widget: string
        hint: Page title
      - name: content
        label: Content
        widget: markdown
        hint: Page content

  - name: posts
    label: Posts
    label_singular: Post
    folder: content/posts
    extension: json
    format: json
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      - name: slug
        label: Slug
        widget: string
        hint: The part of a URL identifies the post
      - name: title
        label: Title
        widget: string
        hint: Post title
      - name: date
        label: Publish Date
        widget: datetime
        format: YYYY-MM-DD
        dateFormat: YYYY-MM-DD
        timeFormat: false
        hint: Date of the post publication
      - name: thumbnail
        label: Thumbnail
        widget: image
        hint: Featured image of the post
      - name: content
        label: Content
        widget: markdown
        hint: Post content
      - name: animal
        label: Animal
        widget: relation
        collection: animals
        value_field: slug
        search_fields: [name]
        display_fields: [name]
        hint: Add an animal to the Animals file of the Meta colection if list is empty
      - name: category
        label: Category
        widget: relation
        collection: categories
        value_field: slug
        search_fields: [name]
        display_fields: [name]
        hint: Add an category to the Categories file of the Meta colection if list is empty
